name: Update Pages

on:
  push:
    paths:
      - '**/*.md'  # Учитываем файлы .md в любых папках

jobs:
  update-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install marked

      - name: Generate pages.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          node -e "
            const fs = require('fs');
            const path = require('path');

            // Функция для извлечения даты из имени файла
            function extractDateFromFilename(filename) {
              const dateRegex = /^(\d{2}\.\d{2}\.\d{4})/;
              const match = filename.match(dateRegex);
              if (match) {
                return match[1]; // Например, '15.10.2023'
              }
              return new Date().toISOString().split('T')[0]; // Если дата не найдена, используем текущую
            }

            // Функция для поиска Markdown-файлов
            function findMarkdownFiles(dir) {
              let results = [];
              const files = fs.readdirSync(dir, { withFileTypes: true });
              for (const file of files) {
                const fullPath = path.join(dir, file.name);
                if (file.isDirectory()) {
                  if (file.name === 'node_modules' || file.name.startsWith('.')) {
                    continue;
                  }
                  results = results.concat(findMarkdownFiles(fullPath));
                } else if (file.name.endsWith('.md')) {
                  results.push(fullPath);
                }
              }
              return results;
            }

            (async () => {
              try {
                const files = findMarkdownFiles('.').map(filePath => ({
                  name: path.basename(filePath),
                  path: filePath
                }));

                console.log('Found files:', files.map(f => f.path));

                const pages = [];
                for (const file of files) {
                  const content = fs.readFileSync(file.path, 'utf8');
                  const slug = file.name.replace('.md', '').toLowerCase().replace(/\s+/g, '-');

                  // Извлекаем дату из имени файла
                  const date = extractDateFromFilename(file.name);

                  // Определяем категорию по имени папки
                  const relativePath = file.path.replace(/\\\\/g, '/');
                  const dirName = path.dirname(relativePath) === '.' ? 'безкатегории' : path.basename(path.dirname(relativePath));

                  // Извлекаем заголовок и описание
                  const titleMatch = content.match(/^# (.+)/m);
                  const title = titleMatch ? titleMatch[1] : file.name.replace('.md', '');
                  const description = content.split('\n').slice(1).join(' ').substring(0, 100) + '...';

                  pages.push({
                    title: title,
                    slug: slug,
                    description: description,
                    link: 'https://Endermanik13.github.io/obsidian/page/' + slug,
                    category: dirName,
                    content: content,
                    date: date
                  });
                }

                // Сортируем страницы по дате
                pages.sort((a, b) => {
                  const dateA = new Date(a.date.split('.').reverse().join('-'));
                  const dateB = new Date(b.date.split('.').reverse().join('-'));
                  return dateB - dateA;
                });
                fs.writeFileSync('pages.json', JSON.stringify(pages, null, 2));
                console.log('Generated pages.json with', pages.length, 'pages');
              } catch (error) {
                console.error('Error in script:', error.message);
                process.exit(1);
              }
            })();
          "

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add pages.json
          git commit -m "Update pages.json with new pages" || echo "No changes to commit"
          git push
